package main

import (
	"os"
	"regexp"

	"gopkg.in/yaml.v3"
)

func loadManifest(path string) (*Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var m Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, err
	}
	return &m, nil
}

func loadLock(path string) (*Lock, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var l Lock
	if err := yaml.Unmarshal(data, &l); err != nil {
		return nil, err
	}
	return &l, nil
}

func saveLock(path string, l *Lock) error {
	return writeYAML(path, l, "# manifest.lock — GENERATED by tools/updater. Do not hand-edit.\n")
}

func writeYAML(path string, v any, header string) error {
	var buf []byte
	enc, err := yaml.Marshal(v)
	if err != nil {
		return err
	}
	buf = append([]byte(header), enc...)
	return os.WriteFile(path, buf, 0o644)
}

// mcFamilyRe matches classic "1.21.11" style versions to derive the "1.21" family.
var mcFamilyRe = regexp.MustCompile(`^(\d+\.\d+)(?:\.\d+)?$`)

// mcFamily derives the Vanilla Tweaks family ("1.21") from an MC version.
// Returns the input unchanged if it does not match the classic scheme.
func mcFamily(mc string) string {
	if m := mcFamilyRe.FindStringSubmatch(mc); m != nil {
		return m[1]
	}
	return mc
}
